'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserDetails", [Namespace]:="http://schemas.datacontract.org/2004/07/DayPlan"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartmnetIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MechanicIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PlanDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PlanTimeFromField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PlanTimeToField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedByField, value) <> true) Then
                    Me.CreatedByField = value
                    Me.RaisePropertyChanged("CreatedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DepartmnetId() As Integer
            Get
                Return Me.DepartmnetIdField
            End Get
            Set
                If (Me.DepartmnetIdField.Equals(value) <> true) Then
                    Me.DepartmnetIdField = value
                    Me.RaisePropertyChanged("DepartmnetId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MechanicId() As String
            Get
                Return Me.MechanicIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MechanicIdField, value) <> true) Then
                    Me.MechanicIdField = value
                    Me.RaisePropertyChanged("MechanicId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PlanDate() As String
            Get
                Return Me.PlanDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PlanDateField, value) <> true) Then
                    Me.PlanDateField = value
                    Me.RaisePropertyChanged("PlanDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PlanTimeFrom() As String
            Get
                Return Me.PlanTimeFromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PlanTimeFromField, value) <> true) Then
                    Me.PlanTimeFromField = value
                    Me.RaisePropertyChanged("PlanTimeFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PlanTimeTo() As String
            Get
                Return Me.PlanTimeToField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PlanTimeToField, value) <> true) Then
                    Me.PlanTimeToField = value
                    Me.RaisePropertyChanged("PlanTimeTo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IDPService")>  _
    Public Interface IDPService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDPService/InsertUserDetails", ReplyAction:="http://tempuri.org/IDPService/InsertUserDetailsResponse")>  _
        Function InsertUserDetails(ByVal userInfo As ServiceReference1.UserDetails) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDPService/InsertUserDetails", ReplyAction:="http://tempuri.org/IDPService/InsertUserDetailsResponse")>  _
        Function InsertUserDetailsAsync(ByVal userInfo As ServiceReference1.UserDetails) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDPServiceChannel
        Inherits ServiceReference1.IDPService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DPServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IDPService)
        Implements ServiceReference1.IDPService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function InsertUserDetails(ByVal userInfo As ServiceReference1.UserDetails) As String Implements ServiceReference1.IDPService.InsertUserDetails
            Return MyBase.Channel.InsertUserDetails(userInfo)
        End Function
        
        Public Function InsertUserDetailsAsync(ByVal userInfo As ServiceReference1.UserDetails) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IDPService.InsertUserDetailsAsync
            Return MyBase.Channel.InsertUserDetailsAsync(userInfo)
        End Function
    End Class
End Namespace
