'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCfHourlyPrice

    '''<summary>
    '''lblHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEditCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEditCap As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIdPrCodeCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIdPrCodeCust As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIdPrCodeRepPkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIdPrCodeRepPkg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''a2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddPrCodeCustT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPrCodeCustT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelPrCodeCustT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelPrCodeCustT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddPrCodeCustB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPrCodeCustB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelPrCodeCustB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelPrCodeCustB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''aheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aheader As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblPrCodeCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrCodeCust As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPrCodeCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrCodeCust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSavePrCodeCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePrCodeCust As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetPrCodeCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetPrCodeCust As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddPrCodeRepPkgT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPrCodeRepPkgT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelPrCodeRepPkgT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelPrCodeRepPkgT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddPrCodeRepPkgB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPrCodeRepPkgB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelPrCodeRepPkgB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelPrCodeRepPkgB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblRPPriceCodeGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPPriceCodeGrp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRPPriceCodeGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPPriceCodeGrp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSavePrCodeRepPkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePrCodeRepPkg As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetPrCodeRepPkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetPrCodeRepPkg As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
